// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Snebur.VisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "Snebur.VisualStudio2022.Rubens Cordeiro.32ce5bbe-ac29-4dbe-8db0-d9e684995904";
        public const string Name = "Snebur.VisualStudio2022";
        public const string Description = @"Snebur extensão ";
        public const string Language = "en-US";
        public const string Version = "23.8.10.244";
        public const string Author = "Rubens Cordeiro";
        public const string Tags = "";
    }
}
