// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Snebur.VisualStudio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSneburVisualStudio2022String = "947d5109-25b9-4a23-a601-dde52a099a53";
        public static Guid guidSneburVisualStudio2022 = new Guid(guidSneburVisualStudio2022String);

        public const string guidMenuSneburCmdSetString = "947d5109-25b9-4a23-a601-dde52a099a53";
        public static Guid guidMenuSneburCmdSet = new Guid(guidMenuSneburCmdSetString);

        public const string guidVSPackageCommandProjectContextMenuCmdSetString = "9a55a2b4-3e29-4359-882b-fa5f51c09300";
        public static Guid guidVSPackageCommandProjectContextMenuCmdSet = new Guid(guidVSPackageCommandProjectContextMenuCmdSetString);

        public const string guidCtxMenuSneburCmdSetString = "679f6e12-e125-4333-96cf-44f7d69f4160";
        public static Guid guidCtxMenuSneburCmdSet = new Guid(guidCtxMenuSneburCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SneburMenuGroup = 0x1020;
        public const int SneburMenu = 0x1021;
        public const int SneburOutputCommand = 0x0050;
        public const int SneburMigrationCommand = 0x0100;
        public const int GoToDefinitionCommand = 0x0101;
        public const int GoToCodeCommand = 0x0102;
        public const int GoToLayoutCommand = 0x0103;
        public const int GoToScssStyleCommand = 0x0104;
        public const int RemoveDominFormatingCommand = 0x0105;
        public const int NormalizarAllProjectsCommand = 0x0106;
        public const int CommandidMenuContextPublicacao = 0x0100;
        public const int MyGroupForCommandsMenuContextProject = 0x1020;
        public const int MyContextoMenuGroup = 0x0200;
        public const int ContextMenu = 0x0201;
        public const int ContextMenuGroup = 0x0202;
        public const int PublishCtxMenuCommand = 0x0204;
    }
}