<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!--<TargetFramework>net7.0</TargetFramework>-->
		<TargetFrameworks>net48</TargetFrameworks>
		<RootNamespace>Snebur.VisualStudio.Compartilhado</RootNamespace>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<Nullable>disable</Nullable>
		<AssemblyName>Snebur.VisualStudio.Compartilhado</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net48' ">

		<Reference Include="System.ServiceModel" />
		<Reference Include="System.Configuration" />
		<Reference Include="System.ComponentModel" />
		<Reference Include="System.ComponentModel" />
		<Reference Include="System.ComponentModel.DataAnnotations" />

		<Reference Include="Microsoft.CSharp" />
		<ProjectReference Include="..\..\..\Snebur.Framework\src\Core.Net48\Snebur.csproj" />

	</ItemGroup>


	<ItemGroup>
		<None Remove="Resources\Modelos\AtributoPartial.ts" />
	</ItemGroup>


	<ItemGroup>
	  <Compile Include="..\..\..\Snebur.Framework\src\Depuracao\Contrato.cs" Link="Depuracao\Contrato.cs" />
	  <Compile Include="..\..\..\Snebur.Framework\src\Depuracao\EnumTipoLog.cs" Link="Depuracao\EnumTipoLog.cs" />
	  <Compile Include="..\..\..\Snebur.Framework\src\Depuracao\Mensagem.cs" Link="Depuracao\Mensagem.cs" />
	  <Compile Include="..\..\..\Snebur.Framework\src\Depuracao\MensagemControleAlterado.cs" Link="Depuracao\MensagemControleAlterado.cs" />
	  <Compile Include="..\..\..\Snebur.Framework\src\Depuracao\MensagemEstiloCssAlterado.cs" Link="Depuracao\MensagemEstiloCssAlterado.cs" />
	  <Compile Include="..\..\..\Snebur.Framework\src\Depuracao\MensagemLog.cs" Link="Depuracao\MensagemLog.cs" />
	  <Compile Include="..\..\..\Snebur.Framework\src\Depuracao\MensagemPing.cs" Link="Depuracao\MensagemPing.cs" />
	  <Compile Include="..\..\..\Snebur.Framework\src\Depuracao\MensagemScriptAlterado.cs" Link="Depuracao\MensagemScriptAlterado.cs" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Resources\Modelos\AtributoPartial.ts" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="HtmlAgilityPack" Version="1.11.46" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Depuracao\" />
	</ItemGroup>

</Project>